name: uni_seg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1
  - torchvision=0.16
  - pytorch-cuda=11.8
  - numpy=1.24
  - scipy=1.11
  - scikit-image=0.21
  - scikit-learn=1.3
  - matplotlib=3.8
  - pandas=1.5
  - tqdm
  - jupyter
  - ipykernel
  - pip
  - pip:
    - timm>=1.0.3
    - huggingface_hub
    - albumentations>=1.3.0
    - opencv-python-headless>=4.8
    - pycocotools>=2.0.7
    - papermill
